/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.*;
import DAO.DataAccess;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author duyhuy
 */
public class app_man extends javax.swing.JFrame {

    /**
     * Creates new form app
     */
    private static String usr = "Q1111";
    private static String pwd = "";
    int x, y;
    public app_man() {
        khoitao();
    }
    public app_man(String pass){
        pwd = pass;
        DataAccess.setUsr_Pwd(usr, pwd);
        khoitao();
    }
    public void khoitao(){
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        try {
            DataAccess.load_driver();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Không load được driver", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_bottom = new javax.swing.JPanel();
        p_header = new javax.swing.JPanel();
        l_h_drag = new javax.swing.JLabel();
        b_h_close = new javax.swing.JButton();
        b_h_mini = new javax.swing.JButton();
        tp_card = new javax.swing.JTabbedPane();
        p_thue = new javax.swing.JPanel();
        p_phong = new javax.swing.JPanel();
        p_hd = new javax.swing.JPanel();
        p_kh = new javax.swing.JPanel();
        p_bc = new javax.swing.JPanel();
        p_dv = new javax.swing.JPanel();
        p_info = new javax.swing.JPanel();
        l_info_dmk = new javax.swing.JLabel();
        l_info_info = new javax.swing.JLabel();
        js_info = new javax.swing.JSeparator();
        l_info_mkc = new javax.swing.JLabel();
        tp_info_mkc = new javax.swing.JPasswordField();
        l_info_mkm = new javax.swing.JLabel();
        tp_info_mkm = new javax.swing.JPasswordField();
        l_info_xnl = new javax.swing.JLabel();
        tp_info_xnl = new javax.swing.JPasswordField();
        l_info_er_mkc = new javax.swing.JLabel();
        l_info_er_mkm = new javax.swing.JLabel();
        l_info_er_xnl = new javax.swing.JLabel();
        b_info_dmk = new javax.swing.JButton();
        b_info_dx = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));

        p_bottom.setBackground(new java.awt.Color(57, 62, 70));
        p_bottom.setPreferredSize(new java.awt.Dimension(100, 25));
        getContentPane().add(p_bottom, java.awt.BorderLayout.PAGE_END);

        p_header.setBackground(new java.awt.Color(57, 62, 70));
        p_header.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p_header.setPreferredSize(new java.awt.Dimension(100, 25));
        p_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_h_drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l_h_dragMouseDragged(evt);
            }
        });
        l_h_drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l_h_dragMousePressed(evt);
            }
        });
        p_header.add(l_h_drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 25));

        b_h_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icon_login/close.png"))); // NOI18N
        b_h_close.setBorder(null);
        b_h_close.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icon_login/close-1.png"))); // NOI18N
        b_h_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_h_closeActionPerformed(evt);
            }
        });
        p_header.add(b_h_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 40, 25));

        b_h_mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icon_login/mini.png"))); // NOI18N
        b_h_mini.setBorder(null);
        b_h_mini.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icon_login/mini-1.png"))); // NOI18N
        b_h_mini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_h_miniActionPerformed(evt);
            }
        });
        p_header.add(b_h_mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 40, 25));

        getContentPane().add(p_header, java.awt.BorderLayout.PAGE_START);

        tp_card.setBackground(new java.awt.Color(238, 238, 238));
        tp_card.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 62, 70)));
        tp_card.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tp_card.setMinimumSize(new java.awt.Dimension(900, 575));
        tp_card.setOpaque(true);
        tp_card.setPreferredSize(new java.awt.Dimension(900, 575));

        javax.swing.GroupLayout p_thueLayout = new javax.swing.GroupLayout(p_thue);
        p_thue.setLayout(p_thueLayout);
        p_thueLayout.setHorizontalGroup(
            p_thueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );
        p_thueLayout.setVerticalGroup(
            p_thueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        tp_card.addTab("    Thuê    ", p_thue);
        tp_card.addTab("   Phòng   ", p_phong);
        tp_card.addTab("     Hóa đơn       ", p_hd);
        tp_card.addTab("    Khách hàng       ", p_kh);
        tp_card.addTab("     Báo cáo        ", p_bc);
        tp_card.addTab("   DV, KM       ", p_dv);

        p_info.setBackground(new java.awt.Color(238, 238, 238));
        p_info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_info_dmk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_info_dmk.setText("Đổi mật khẩu ");
        p_info.add(l_info_dmk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        l_info_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icon_login/info-app-background.png"))); // NOI18N
        p_info.add(l_info_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        js_info.setOrientation(javax.swing.SwingConstants.VERTICAL);
        p_info.add(js_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 0, 10, 520));

        l_info_mkc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        l_info_mkc.setText("Mật khẩu cũ");
        p_info.add(l_info_mkc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        tp_info_mkc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tp_info_mkc.setText("jPassword");
        tp_info_mkc.setNextFocusableComponent(tp_info_mkm);
        tp_info_mkc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tp_info_mkcFocusGained(evt);
            }
        });
        p_info.add(tp_info_mkc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 170, -1));

        l_info_mkm.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        l_info_mkm.setText("Mật khẩu mới");
        p_info.add(l_info_mkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        tp_info_mkm.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tp_info_mkm.setText("jPassword");
        tp_info_mkm.setNextFocusableComponent(tp_info_xnl);
        tp_info_mkm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tp_info_mkmFocusGained(evt);
            }
        });
        p_info.add(tp_info_mkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 170, -1));

        l_info_xnl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        l_info_xnl.setText("Xác nhận lại");
        p_info.add(l_info_xnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        tp_info_xnl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tp_info_xnl.setText("jPassword");
        tp_info_xnl.setNextFocusableComponent(b_info_dmk);
        tp_info_xnl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tp_info_xnlFocusGained(evt);
            }
        });
        p_info.add(tp_info_xnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 170, -1));

        l_info_er_mkc.setForeground(new java.awt.Color(153, 0, 0));
        p_info.add(l_info_er_mkc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 170, 20));

        l_info_er_mkm.setForeground(new java.awt.Color(153, 0, 0));
        p_info.add(l_info_er_mkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, 20));

        l_info_er_xnl.setForeground(new java.awt.Color(153, 0, 0));
        p_info.add(l_info_er_xnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 170, 20));

        b_info_dmk.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        b_info_dmk.setText("Đổi mật khẩu");
        b_info_dmk.setNextFocusableComponent(b_info_dx);
        b_info_dmk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_info_dmkActionPerformed(evt);
            }
        });
        p_info.add(b_info_dmk, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 130, -1));

        b_info_dx.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        b_info_dx.setText("Đăng xuất");
        b_info_dx.setNextFocusableComponent(tp_info_mkc);
        b_info_dx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_info_dxActionPerformed(evt);
            }
        });
        p_info.add(b_info_dx, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        tp_card.addTab("       Info app        ", p_info);

        getContentPane().add(tp_card, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_h_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_h_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_b_h_closeActionPerformed

    private void b_h_miniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_h_miniActionPerformed
        // TODO add your handling code here:
        this.setState(app_man.ICONIFIED);
    }//GEN-LAST:event_b_h_miniActionPerformed

    private void l_h_dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_h_dragMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_l_h_dragMousePressed

    private void l_h_dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_h_dragMouseDragged
        // TODO add your handling code here:
        int _x = evt.getXOnScreen();
        int _y = evt.getYOnScreen();
        this.setLocation(_x-x, _y-y);
    }//GEN-LAST:event_l_h_dragMouseDragged

    private void tp_info_mkcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tp_info_mkcFocusGained
        // TODO add your handling code here:
        tp_info_mkc.setText("");
    }//GEN-LAST:event_tp_info_mkcFocusGained

    private void tp_info_mkmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tp_info_mkmFocusGained
        // TODO add your handling code here:
        tp_info_mkm.setText("");
    }//GEN-LAST:event_tp_info_mkmFocusGained

    private void tp_info_xnlFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tp_info_xnlFocusGained
        // TODO add your handling code here:
        tp_info_xnl.setText("");
    }//GEN-LAST:event_tp_info_xnlFocusGained

    private void b_info_dmkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_info_dmkActionPerformed
        String mkc = tp_info_mkc.getText();
        String mkm = tp_info_mkm.getText();
        String xnl = tp_info_xnl.getText();

        NGUOIDUNG_BUS up_ql = null;
        try {
            up_ql = new NGUOIDUNG_BUS();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            up_ql.doimk_QL(pwd, mkc, mkm, xnl);
        } catch (Exception ex) {
            if(ex.getMessage().contains("*M")){
                l_info_er_mkc.setText(ex.getMessage());
                l_info_er_mkm.setText("");
                l_info_er_xnl.setText("");
            }
            else if (ex.getMessage().contains("*T")){
                l_info_er_mkc.setText("");
                l_info_er_mkm.setText(ex.getMessage());
                l_info_er_xnl.setText("");
            }
            else if (ex.getMessage().contains("*X")){
                l_info_er_mkc.setText("");
                l_info_er_mkm.setText("");
                l_info_er_xnl.setText(ex.getMessage());
            }
            else{
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
                l_info_er_mkc.setText("");
                l_info_er_mkm.setText("");
                l_info_er_xnl.setText("");
            }
            return;
        }
        l_info_er_mkc.setText("");
        l_info_er_mkm.setText("");
        l_info_er_xnl.setText("");
        JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công", "Thông báo", JOptionPane.NO_OPTION);
        
    }//GEN-LAST:event_b_info_dmkActionPerformed

    private void b_info_dxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_info_dxActionPerformed
        // TODO add your handling code here:
        login logi = new login();
        logi.setVisible(true);
        b_h_close.doClick();
    }//GEN-LAST:event_b_info_dxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.install();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new app_man("123").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_h_close;
    private javax.swing.JButton b_h_mini;
    private javax.swing.JButton b_info_dmk;
    private javax.swing.JButton b_info_dx;
    private javax.swing.JSeparator js_info;
    private javax.swing.JLabel l_h_drag;
    private javax.swing.JLabel l_info_dmk;
    private javax.swing.JLabel l_info_er_mkc;
    private javax.swing.JLabel l_info_er_mkm;
    private javax.swing.JLabel l_info_er_xnl;
    private javax.swing.JLabel l_info_info;
    private javax.swing.JLabel l_info_mkc;
    private javax.swing.JLabel l_info_mkm;
    private javax.swing.JLabel l_info_xnl;
    private javax.swing.JPanel p_bc;
    private javax.swing.JPanel p_bottom;
    private javax.swing.JPanel p_dv;
    private javax.swing.JPanel p_hd;
    private javax.swing.JPanel p_header;
    private javax.swing.JPanel p_info;
    private javax.swing.JPanel p_kh;
    private javax.swing.JPanel p_phong;
    private javax.swing.JPanel p_thue;
    private javax.swing.JTabbedPane tp_card;
    private javax.swing.JPasswordField tp_info_mkc;
    private javax.swing.JPasswordField tp_info_mkm;
    private javax.swing.JPasswordField tp_info_xnl;
    // End of variables declaration//GEN-END:variables
}
